name: Create Plugin Release

on:
  push:
    tags:
      - 'v*'  # Trigger when new tags starting with 'v' are pushed

jobs:
  build:
    runs-on: self-hosted
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '24'
        cache: 'npm'

    - name: Install npm dependencies
      run: npm ci

    - name: Build React assets
      run: npm run build

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        tools: composer

    - name: Install Composer dependencies (production only)
      run: ./build.sh

    - name: Create plugin ZIP file
      run: |
       wp dist-archive . --plugin-dirname=formularer-for-awork-one

    - name: Upload release assets
      uses: softprops/action-gh-release@v1
      with:
        files: ../formularer-for-awork-one.*.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Clean archived file
      run: |
        rm ../formularer-for-awork-one.*.zip
